## Code

In [1]:
from PIL import Image, ImageDraw, ImageFilter                                   
import sys                                                                      
import numpy as np 

In [2]:
im = Image.open('Data_Image.png')
print(im)

<PIL.PngImagePlugin.PngImageFile image mode=RGB size=620x349 at 0x7FDA47F8F490>


In [3]:
print(im.format, im.size, im.mode)

PNG (620, 349) RGB


In [4]:
image_array = np.array(im)
shape = image_array.shape
shape

(349, 620, 3)

In [5]:
image_array

array([[[153, 148, 142],
        [152, 147, 141],
        [150, 145, 139],
        ...,
        [125, 119, 119],
        [125, 119, 119],
        [126, 120, 120]],

       [[149, 144, 138],
        [148, 143, 137],
        [147, 142, 136],
        ...,
        [123, 117, 117],
        [123, 117, 117],
        [124, 118, 118]],

       [[147, 142, 136],
        [147, 142, 136],
        [146, 142, 133],
        ...,
        [122, 116, 116],
        [122, 116, 116],
        [123, 117, 117]],

       ...,

       [[128, 127, 125],
        [128, 127, 125],
        [127, 126, 124],
        ...,
        [123, 119, 118],
        [129, 125, 124],
        [126, 122, 121]],

       [[133, 132, 130],
        [128, 127, 125],
        [132, 131, 129],
        ...,
        [127, 123, 122],
        [132, 128, 127],
        [128, 124, 123]],

       [[134, 133, 131],
        [131, 130, 128],
        [133, 132, 130],
        ...,
        [126, 122, 121],
        [126, 122, 121],
        [121, 117, 116]]

In [6]:
def repeat_to_length(string_to_expand, length):
    return (string_to_expand * (int(length/len(string_to_expand))+1))[:length]

In [7]:
string2 = 'ananthadip'
if (len(string2)>im.size[0]):
    key = list(string2[0:im.size[0]])
else:
    new_str = repeat_to_length(string2,im.size[0])
    key = list(new_str)

In [8]:
key

['a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a',
 'd',
 'i',
 'p',
 'a',
 'n',
 'a',
 'n',
 't',
 'h',
 'a'

In [9]:
key=[ord(c) for c in key]

In [10]:
key

[97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 104,
 97,
 100,
 105,
 112,
 97,
 110,
 97,
 110,
 116,
 10

In [11]:
key_updated = []

for i in key:
    for k in range(shape[2]):
        key_updated.append(i)
    

In [12]:
key_updated = [str(i) for i in key_updated]

In [13]:
key_updated

['97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '116',
 '116',
 '116',
 '104',
 '104',
 '104',
 '97',
 '97',
 '97',
 '100',
 '100',
 '100',
 '105',
 '105',
 '105',
 '112',
 '112',
 '112',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '116',
 '116',
 '116',
 '104',
 '104',
 '104',
 '97',
 '97',
 '97',
 '100',
 '100',
 '100',
 '105',
 '105',
 '105',
 '112',
 '112',
 '112',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '116',
 '116',
 '116',
 '104',
 '104',
 '104',
 '97',
 '97',
 '97',
 '100',
 '100',
 '100',
 '105',
 '105',
 '105',
 '112',
 '112',
 '112',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '116',
 '116',
 '116',
 '104',
 '104',
 '104',
 '97',
 '97',
 '97',
 '100',
 '100',
 '100',
 '105',
 '105',
 '105',
 '112',
 '112',
 '112',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '

In [14]:
key_string = ",".join(key_updated)

In [15]:
key_string

'97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,

In [16]:
key_buffer = ''
for i in range(im.size[1]):
    if (i == 0):
        key_buffer += key_string
    else:
        key_buffer +=  ','+key_string


In [17]:
key_buffer

'97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,97,97,97,110,110,110,97,97,97,110,110,110,116,116,116,104,104,104,97,97,97,100,100,100,105,105,105,112,112,112,

In [18]:
key = key_buffer.split(',')

In [19]:
key

['97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '116',
 '116',
 '116',
 '104',
 '104',
 '104',
 '97',
 '97',
 '97',
 '100',
 '100',
 '100',
 '105',
 '105',
 '105',
 '112',
 '112',
 '112',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '116',
 '116',
 '116',
 '104',
 '104',
 '104',
 '97',
 '97',
 '97',
 '100',
 '100',
 '100',
 '105',
 '105',
 '105',
 '112',
 '112',
 '112',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '116',
 '116',
 '116',
 '104',
 '104',
 '104',
 '97',
 '97',
 '97',
 '100',
 '100',
 '100',
 '105',
 '105',
 '105',
 '112',
 '112',
 '112',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '116',
 '116',
 '116',
 '104',
 '104',
 '104',
 '97',
 '97',
 '97',
 '100',
 '100',
 '100',
 '105',
 '105',
 '105',
 '112',
 '112',
 '112',
 '97',
 '97',
 '97',
 '110',
 '110',
 '110',
 '97',
 '97',
 '97',
 '110',
 '

In [20]:
len(key)

649140

In [21]:
key = [int(i) for i in key]

In [22]:
key

[97,
 97,
 97,
 110,
 110,
 110,
 97,
 97,
 97,
 110,
 110,
 110,
 116,
 116,
 116,
 104,
 104,
 104,
 97,
 97,
 97,
 100,
 100,
 100,
 105,
 105,
 105,
 112,
 112,
 112,
 97,
 97,
 97,
 110,
 110,
 110,
 97,
 97,
 97,
 110,
 110,
 110,
 116,
 116,
 116,
 104,
 104,
 104,
 97,
 97,
 97,
 100,
 100,
 100,
 105,
 105,
 105,
 112,
 112,
 112,
 97,
 97,
 97,
 110,
 110,
 110,
 97,
 97,
 97,
 110,
 110,
 110,
 116,
 116,
 116,
 104,
 104,
 104,
 97,
 97,
 97,
 100,
 100,
 100,
 105,
 105,
 105,
 112,
 112,
 112,
 97,
 97,
 97,
 110,
 110,
 110,
 97,
 97,
 97,
 110,
 110,
 110,
 116,
 116,
 116,
 104,
 104,
 104,
 97,
 97,
 97,
 100,
 100,
 100,
 105,
 105,
 105,
 112,
 112,
 112,
 97,
 97,
 97,
 110,
 110,
 110,
 97,
 97,
 97,
 110,
 110,
 110,
 116,
 116,
 116,
 104,
 104,
 104,
 97,
 97,
 97,
 100,
 100,
 100,
 105,
 105,
 105,
 112,
 112,
 112,
 97,
 97,
 97,
 110,
 110,
 110,
 97,
 97,
 97,
 110,
 110,
 110,
 116,
 116,
 116,
 104,
 104,
 104,
 97,
 97,
 97,
 100,
 100,
 100,
 105,
 105

In [23]:
key = np.array(key)

In [24]:
final_key = key.reshape(shape[0], shape[1], shape[2])

In [25]:
final_key

array([[[ 97,  97,  97],
        [110, 110, 110],
        [ 97,  97,  97],
        ...,
        [100, 100, 100],
        [105, 105, 105],
        [112, 112, 112]],

       [[ 97,  97,  97],
        [110, 110, 110],
        [ 97,  97,  97],
        ...,
        [100, 100, 100],
        [105, 105, 105],
        [112, 112, 112]],

       [[ 97,  97,  97],
        [110, 110, 110],
        [ 97,  97,  97],
        ...,
        [100, 100, 100],
        [105, 105, 105],
        [112, 112, 112]],

       ...,

       [[ 97,  97,  97],
        [110, 110, 110],
        [ 97,  97,  97],
        ...,
        [100, 100, 100],
        [105, 105, 105],
        [112, 112, 112]],

       [[ 97,  97,  97],
        [110, 110, 110],
        [ 97,  97,  97],
        ...,
        [100, 100, 100],
        [105, 105, 105],
        [112, 112, 112]],

       [[ 97,  97,  97],
        [110, 110, 110],
        [ 97,  97,  97],
        ...,
        [100, 100, 100],
        [105, 105, 105],
        [112, 112, 112]]

In [26]:
encrypted = final_key * image_array
print(encrypted)

[[[14841 14356 13774]
  [16720 16170 15510]
  [14550 14065 13483]
  ...
  [12500 11900 11900]
  [13125 12495 12495]
  [14112 13440 13440]]

 [[14453 13968 13386]
  [16280 15730 15070]
  [14259 13774 13192]
  ...
  [12300 11700 11700]
  [12915 12285 12285]
  [13888 13216 13216]]

 [[14259 13774 13192]
  [16170 15620 14960]
  [14162 13774 12901]
  ...
  [12200 11600 11600]
  [12810 12180 12180]
  [13776 13104 13104]]

 ...

 [[12416 12319 12125]
  [14080 13970 13750]
  [12319 12222 12028]
  ...
  [12300 11900 11800]
  [13545 13125 13020]
  [14112 13664 13552]]

 [[12901 12804 12610]
  [14080 13970 13750]
  [12804 12707 12513]
  ...
  [12700 12300 12200]
  [13860 13440 13335]
  [14336 13888 13776]]

 [[12998 12901 12707]
  [14410 14300 14080]
  [12901 12804 12610]
  ...
  [12600 12200 12100]
  [13230 12810 12705]
  [13552 13104 12992]]]


In [27]:
im1 = Image.fromarray((encrypted).astype(np.uint8))                       
print(im1)

<PIL.Image.Image image mode=RGB size=620x349 at 0x7FDA4C18AFD0>


In [31]:
im1.save("Encrypted.png") 

![text](Encrypted.png)

In [32]:
decrypted = encrypted / final_key

In [33]:
import cv2 
from numba import njit,prange
import random

In [34]:
amaze = np.random.normal(0, 2, decrypted.shape)
Decrypt = decrypted - amaze

im2 = Image.fromarray((Decrypt).astype(np.uint8))

In [35]:
im2.save("Decrypted.png")

![title](Decrypted.png)

In [36]:
@njit
def padding(img,pad):
    padded_img = np.zeros((img.shape[0]+2*pad,img.shape[1]+2*pad))
    padded_img[pad:-pad,pad:-pad] = img
    return padded_img

@njit(parallel=True)
def AdaptiveMedianFilter(img,s=3,sMax=11):
    if len(img.shape) == 3:
        raise Exception ("Single channel image only")

    H,W = img.shape
    a = sMax//2
    padded_img = padding(img,a)

    f_img = np.zeros(padded_img.shape)

    for i in prange(a,H+a+1):
        for j in range(a,W+a+1):
            value = Lvl_A(padded_img,i,j,s,sMax)
            f_img[i,j] = value

    return f_img[a:-a,a:-a] 

@njit
def Lvl_A(mat,x,y,s,sMax):
    window = mat[x-(s//2):x+(s//2)+1,y-(s//2):y+(s//2)+1]
    Zmin = np.min(window)
    Zmed = np.median(window)
    Zmax = np.max(window)

    A1 = Zmed - Zmin
    A2 = Zmed - Zmax

    if A1 > 0 and A2 < 0:
        return Lvl_B(window, Zmin, Zmed, Zmax)
    else:
        s += 2 
        if s <= sMax:
            return Lvl_A(mat,x,y,s,sMax)
        else:
             return Zmed

@njit
def Lvl_B(window, Zmin, Zmed, Zmax):
    h,w = window.shape

    Zxy = window[h//2,w//2]
    B1 = Zxy - Zmin
    B2 = Zxy - Zmax

    if B1 > 0 and B2 < 0 :
        return Zxy
    else:
        return Zmed

#function that adds salt and pepper noise
def sp_noise(image,prob):
    output = np.zeros(image.shape,np.uint8)
    thres = 1 - prob 
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            rdn = random.random()
            if rdn < prob:
                output[i][j] = 0
            elif rdn > thres:
                output[i][j] = 255
            else:
                output[i][j] = image[i][j]
    return output

#read and resize image
img_noisy1 = cv2.imread('decrypted.png', 1)
a1 = img_noisy1.shape[0]
a2 = img_noisy1.shape[1]
img_noisy1 = cv2.resize(img_noisy1,(a2,a1))

#add noise
#img_noisy1 = sp_noise(img_noisy1,0.1)

#split into colour channels and perform filtering on each channel
b,g,r = cv2.split(img_noisy1)
bnew = AdaptiveMedianFilter(b)
gnew = AdaptiveMedianFilter(g)
rnew = AdaptiveMedianFilter(r)

#merge colour channels
t = cv2.merge((bnew,gnew,rnew))
t = t.astype(np.uint8) 

#view and save image
numpy_horizontal = np.hstack((img_noisy1, t))
#cv2.imshow('Noisy vs De-noised', numpy_horizontal)
#cv2.waitKey(0)
#cv2.destroyAllWindows()
cv2.imwrite('De-noised.png', t)

True

![title](De-noised.png)

In [37]:
from skimage.exposure import adjust_sigmoid
from functools import reduce
import matplotlib.pyplot as plt


In [38]:
import ipywidgets as widgets


#gamma transformations
def gamma(imag,n):
	img = cv2.imread(imag)
	gamma = np.array(255*(img/255)**n,dtype='uint8')
	cv2.imwrite('Gamma_Transformed_'+str(n)+'.jpg',gamma)

#pixel transformation with adding all the pixels by value of n
def pixel_transformation_add(img,n):
	# n is number to be added
	image=Image.open(img)
	image_array=np.asarray(image)
	image_array_add=np.add(image_array,n)
	image_add=Image.fromarray(image_array_add)
	#plt.imshow(image_add)
	image_add.save('Pixel_Transformation_added'+str(n)+'.jpg')

#contrast stretching 
def contrast_stretching(image):
	im=cv2.imread(image)
	# Finding the maximum and minimum pixel values
	b = im.max()
	a = im.min()
	print(a,b)
	# Converting im1 to float.
	c = im.astype(float)
	# Contrast stretching transformation.
	im1 = 255.0*(c-a)/(b-a+0.0000001)
	# Saving im2 as contrast_output.png
	cv2.imwrite('Contrast_Stretch.jpg', im1) 

#histogram equalization
def histogram_equalization(img):
	img1=cv2.imread(img)
	# convert 2D to a 1D array
	f1=img1.flatten()
	#histogram and the bins of the image are computed
	hist,bins=np.histogram(img1,256,[0,255])
	#cumulative distribution function
	cdf=hist.cumsum()
	# Places where cdf=0 is masked or ignored and
	# rest is stored in cdf_m.
	cdf_m = np.ma.masked_equal(cdf,0)
	# Histogram equalization is performed.
	num_cdf_m = (cdf_m - cdf_m.min())*255
	den_cdf_m = (cdf_m.max()-cdf_m.min())
	cdf_m = num_cdf_m/den_cdf_m
	# The masked places in cdf_m are now 0.
	cdf = np.ma.filled(cdf_m,0).astype('uint8')
	# cdf values are assigned in the flattened array.
	im2 = cdf[f1]
	# im2 is 1D so we use reshape command to.
	# make it into 2D.
	im3=np.reshape(im2,img1.shape)
	#plt.imshow(im3)
	cv2.imwrite('Hist_Equalization.jpg',im3)

def sigmoid_correction(img,cutoff,gain):
	# Reading the image.
	img1 = cv2.imread(img)
	# Applying Sigmoid correction.
	img2 = adjust_sigmoid(img1, cutoff=cutoff, gain=gain)
	# Saving img2.
	#plt.imshow(img2)
	cv2.imwrite('Sigmoid_Corrected.jpg', img2)

# Decorrelation stretch of image
#tol -- upper and lower limit of contrast stretching
def decorrstretch(img, tol=None):
    # save the original shape
    A=cv2.imread(img)
    orig_shape = A.shape
    # reshape the image
    #         B G R
    # pixel 1 .
    # pixel 2   .
    #  . . .      .
    A = A.reshape((-1,3)).astype(np.float)
    # covariance matrix of A
    cov = np.cov(A.T)
    # source and target sigma
    sigma = np.diag(np.sqrt(cov.diagonal()))
    # eigen decomposition of covariance matrix
    eigval, V = np.linalg.eig(cov)
    # stretch matrix
    S = np.diag(1/np.sqrt(eigval))
    # compute mean of each color
    mean = np.mean(A, axis=0)
    # substract the mean from image
    A -= mean
    # compute the transformation matrix
    T = reduce(np.dot, [sigma, V, S, V.T])
    # compute offset 
    offset = mean - np.dot(mean, T)
    # transform the image
    A = np.dot(A, T)
    # add the mean and offset
    A += mean + offset
    # restore original shape
    B = A.reshape(orig_shape)
    # for each color...
    for b in range(3):
        # apply contrast stretching if requested
        if tol:
            # find lower and upper limit for contrast stretching
            low, high = np.percentile(B[:,:,b], 100*tol), np.percentile(B[:,:,b], 100-100*tol)
            B[B<low] = low
            B[B>high] = high
        # ...rescale the color values to 0..255
        B[:,:,b] = 255 * (B[:,:,b] - B[:,:,b].min())/(B[:,:,b].max() - B[:,:,b].min())
    # return it as uint8 (byte) image
    cv2.imwrite('Decorrelated_stretched.jpg', B)

def unsharp_masking(img):
	image = cv2.imread(img)
	gauss_mask = cv2.GaussianBlur(image, (9, 9), 10.0)
	image_sharp = cv2.addWeighted(image, 2, gauss_mask, -1, 0)
	# equivalent expr
	#image = (image*1.5) - (gauss_mask*0.5)     # may produce artifact due to lack of saturation maths
	cv2.imwrite('Sharpened.jpg',image_sharp)

In [39]:
img_path='De-noised.png' # path to input image
pixel_transformation_add(img_path,5)
gamma(img_path, 2.2)
contrast_stretching(img_path)
histogram_equalization(img_path)
sigmoid_correction(img_path, 0.5, 15)
decorrstretch(img_path)
unsharp_masking(img_path)

0 254


## Image after Pixel transformation

![text](Pixel_Transformation_added5.jpg)

## Image after Gamma transformation
![text](Gamma_Transformed_2.2.jpg)

## Image after Contrast Stretching

![text](Contrast_Stretch.jpg)

## Image after histogram equalisation

![text](Hist_Equalization.jpg)

## Image after sigmoid correction

![text](Sigmoid_Corrected.jpg)

## Image after Decorrstretch

![text](Decorrelated_Stretched.jpg)

## Image after Unsharp masking

![text](Sharpened.jpg)